import { PublicKey } from '@solana/web3.js';

export type PerpMarketConfig = {
  fullName?: string;
  category?: string[];
  symbol: string;
  baseAssetSymbol: string;
  marketIndex: number;
  launchTs?: number;
  oracle: PublicKey;
  oracleSource: string;
};

export const DevnetPerpMarkets: PerpMarketConfig[] = [
  {
    fullName: 'Solana',
    category: ['L1', 'Infra'],
    symbol: 'SOL-PERP',
    baseAssetSymbol: 'SOL',
    marketIndex: 0,
    oracle: new PublicKey('3m6i4RFWEDw2Ft4tFHPJtYgmpPe21k56M3FHeWYrgGBz'),
    launchTs: 1655751353000,
    oracleSource: 'PYTH_LAZER',
  },
  {
    fullName: 'Bitcoin',
    category: ['L1', 'Payment'],
    symbol: 'BTC-PERP',
    baseAssetSymbol: 'BTC',
    marketIndex: 1,
    oracle: new PublicKey('35MbvS1Juz2wf7GsyHrkCw8yfKciRLxVpEhfZDZFrB4R'),
    launchTs: 1655751353000,
    oracleSource: 'PYTH_LAZER',
  },
  {
    fullName: 'Ethereum',
    category: ['L1', 'Infra'],
    symbol: 'ETH-PERP',
    baseAssetSymbol: 'ETH',
    marketIndex: 2,
    oracle: new PublicKey('93FG52TzNKCnMiasV14Ba34BYcHDb9p4zK4GjZnLwqWR'),
    launchTs: 1637691133472,
    oracleSource: 'PYTH_LAZER',
  },
  {
    fullName: 'Aptos',
    category: ['L1', 'Infra'],
    symbol: 'APT-PERP',
    baseAssetSymbol: 'APT',
    marketIndex: 3,
    oracle: new PublicKey('79EWaCYU9jiQN8SbvVzGFAhAncUZYp3PjNg7KxmN5cLE'),
    launchTs: 1675610186000,
    oracleSource: 'PYTH_PULL',
  },
  {
    fullName: 'Bonk',
    category: ['Meme', 'Dog'],
    symbol: '1MBONK-PERP',
    baseAssetSymbol: '1MBONK',
    marketIndex: 4,
    oracle: new PublicKey('BERaNi6cpEresbq6HC1EQGaB1H1UjvEo4NGnmYSSJof4'),
    launchTs: 1677068931000,
    oracleSource: 'PYTH_LAZER_1M',
  },
  {
    fullName: 'Polygon',
    category: ['L2', 'Infra'],
    symbol: 'POL-PERP',
    baseAssetSymbol: 'POL',
    marketIndex: 5,
    oracle: new PublicKey('BrzyDgwELy4jjjsqLQpBeUxzrsueYyMhuWpYBaUYcXvi'),
    launchTs: 1677690149000,
    oracleSource: 'PYTH_PULL',
  },
  {
    fullName: 'Arbitrum',
    category: ['L2', 'Infra'],
    symbol: 'ARB-PERP',
    baseAssetSymbol: 'ARB',
    marketIndex: 6,
    oracle: new PublicKey('8ocfAdqVRnzvfdubQaTxar4Kz5HJhNbPNmkLxswqiHUD'),
    launchTs: 1679501812000,
    oracleSource: 'PYTH_PULL',
  },
  {
    fullName: 'Doge',
    category: ['Meme', 'Dog'],
    symbol: 'DOGE-PERP',
    baseAssetSymbol: 'DOGE',
    marketIndex: 7,
    oracle: new PublicKey('23y63pHVwKfYSCDFdiGRaGbTYWoyr8UzhUE7zukyf6gK'),
    launchTs: 1680808053000,
    oracleSource: 'PYTH_PULL',
  },
  {
    fullName: 'Binance Coin',
    category: ['Exchange'],
    symbol: 'BNB-PERP',
    baseAssetSymbol: 'BNB',
    marketIndex: 8,
    oracle: new PublicKey('Dk8eWjuQHMbxJAwB9Sg7pXQPH4kgbg8qZGcUrWcD9gTm'),
    launchTs: 1680808053000,
    oracleSource: 'PYTH_PULL',
  },
  {
    fullName: 'Sui',
    category: ['L1'],
    symbol: 'SUI-PERP',
    baseAssetSymbol: 'SUI',
    marketIndex: 9,
    oracle: new PublicKey('HBordkz5YxjzNURmKUY4vfEYFG9fZyZNeNF1VDLMoemT'),
    launchTs: 1683125906000,
    oracleSource: 'PYTH_PULL',
  },
  {
    fullName: 'Pepe',
    category: ['Meme'],
    symbol: '1MPEPE-PERP',
    baseAssetSymbol: '1MPEPE',
    marketIndex: 10,
    oracle: new PublicKey('CLxofhtzvLiErpn25wvUzpZXEqBhuZ6WMEckEraxyuGt'),
    launchTs: 1683781239000,
    oracleSource: 'PYTH_1M_PULL',
  },
  {
    fullName: 'OP',
    category: ['L2', 'Infra'],
    symbol: 'OP-PERP',
    baseAssetSymbol: 'OP',
    marketIndex: 11,
    oracle: new PublicKey('C9Zi2Y3Mt6Zt6pcFvobN3N29HcrzKujPAPBDDTDRcUa2'),
    launchTs: 1686091480000,
    oracleSource: 'PYTH_PULL',
  },
  {
    fullName: 'RENDER',
    category: ['Infra'],
    symbol: 'RENDER-PERP',
    baseAssetSymbol: 'RENDER',
    marketIndex: 12,
    oracle: new PublicKey('8TQztfGcNjHGRusX4ejQQtPZs3Ypczt9jWF6pkgQMqUX'),
    launchTs: 1687201081000,
    oracleSource: 'PYTH_PULL',
  },
  {
    fullName: 'XRP',
    category: ['Payments'],
    symbol: 'XRP-PERP',
    baseAssetSymbol: 'XRP',
    marketIndex: 13,
    oracle: new PublicKey('9757epAjXWCWQH98kyK9vzgehd1XDVEf7joNHUaKk3iV'),
    launchTs: 1689270550000,
    oracleSource: 'PYTH_PULL',
  },
  {
    fullName: 'HNT',
    category: ['IoT'],
    symbol: 'HNT-PERP',
    baseAssetSymbol: 'HNT',
    marketIndex: 14,
    oracle: new PublicKey('9b1rcK9RUPK2vAqwNYCYEG34gUVpS2WGs2YCZZy2X5Tb'),
    launchTs: 1692294955000,
    oracleSource: 'PYTH_PULL',
  },
  {
    fullName: 'INJ',
    category: ['L1', 'Exchange'],
    symbol: 'INJ-PERP',
    baseAssetSymbol: 'INJ',
    marketIndex: 15,
    oracle: new PublicKey('BfXcyDWJmYADa5eZD7gySSDd6giqgjvm7xsAhQ239SUD'),
    launchTs: 1698074659000,
    oracleSource: 'PYTH_PULL',
  },
  {
    fullName: 'LINK',
    category: ['Oracle'],
    symbol: 'LINK-PERP',
    baseAssetSymbol: 'LINK',
    marketIndex: 16,
    oracle: new PublicKey('Gwvob7yoLMgQRVWjScCRyQFMsgpRKrSAYisYEyjDJwEp'),
    launchTs: 1698074659000,
    oracleSource: 'PYTH_PULL',
  },
  {
    fullName: 'Rollbit',
    category: ['Exchange'],
    symbol: 'RLB-PERP',
    baseAssetSymbol: 'RLB',
    marketIndex: 17,
    oracle: new PublicKey('4CyhPqyVK3UQHFWhEpk91Aw4WbBsN3JtyosXH6zjoRqG'),
    launchTs: 1699265968000,
    oracleSource: 'PYTH_PULL',
  },
  {
    fullName: 'Pyth',
    category: ['Oracle'],
    symbol: 'PYTH-PERP',
    baseAssetSymbol: 'PYTH',
    marketIndex: 18,
    oracle: new PublicKey('GqkCu7CbsPVz1H6W6AAHuReqbJckYG59TXz7Y5HDV7hr'),
    launchTs: 1700542800000,
    oracleSource: 'PYTH_PULL',
  },
  {
    fullName: 'Celestia',
    category: ['Data'],
    symbol: 'TIA-PERP',
    baseAssetSymbol: 'TIA',
    marketIndex: 19,
    oracle: new PublicKey('C6LHPUrgjrgo5eNUitC8raNEdEttfoRhmqdJ3BHVBJhi'),
    launchTs: 1701880540000,
    oracleSource: 'PYTH_PULL',
  },
];
